apiVersion: batch/v1
kind: CronJob
metadata:
  name: backdoor-shell
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: job
            image: busybox
            command:
              - /bin/sh
              - -c
              - "echo Running backdoor job; sleep 30"
          restartPolicy: OnFailure
